### ISSUE TITLE
Allow to skip python installation

### ISSUE THREAD

**Issue by clalarco** [marian-code/python-lint-annotate#15]
In some cases, the project uses multiple requirements.txt file (for example, for build and testing) or even a different build system such as Poetry. In those cases, some import checks will fail because the steps are using a different python installation.

The proposal is to add a new parameter, such as `require-python-installation` (true as default), to skip all the installations and rely on the previous steps in the user's workflow.

**Comment by marian-code** [comment]
Thanks for the suggestion. While I'd like to implement it I'm a bit short on time right now and don't know when it will change. So if you'd like to make a PR that would be very welcome :blush: If not I'll try to do this myself just don't know when.

**Comment by clalarco** [comment]
Hi, @marian-code, I added a PR, please review.
